DROP TABLE IF EXISTS producer CASCADE;

DROP TABLE IF EXISTS country CASCADE;

DROP TABLE IF EXISTS city CASCADE;

DROP TABLE IF EXISTS music_group CASCADE;

DROP TABLE IF EXISTS producer_of_group CASCADE;

DROP TABLE IF EXISTS genre CASCADE;

DROP TABLE IF EXISTS genre_of_group CASCADE;

DROP TABLE IF EXISTS musician CASCADE;

DROP TABLE IF EXISTS group_member CASCADE;

DROP TABLE IF EXISTS instrument_class CASCADE;

DROP TABLE IF EXISTS instrument CASCADE;

DROP TABLE IF EXISTS musician_instrument CASCADE;

DROP TABLE IF EXISTS album CASCADE;

DROP TABLE IF EXISTS genre_of_album CASCADE;

DROP TABLE IF EXISTS group_on_album CASCADE;

DROP TABLE IF EXISTS song CASCADE;

DROP TABLE IF EXISTS genre_of_song CASCADE;

DROP TABLE IF EXISTS tour CASCADE;

DROP TABLE IF EXISTS group_in_tour CASCADE;

DROP TABLE IF EXISTS concert CASCADE;

DROP TABLE IF EXISTS group_on_song CASCADE;

DROP TABLE IF EXISTS song_on_album CASCADE;